# 문자열 관련 함수

In [3]:
# 여러개의 벡터를 하나로 만들기

xx <- c('a','b','c','d','e')
xx
xx[1:2]
paste(xx[1], xx[2])

[1] "a" "b" "c" "d" "e"

[1] "a" "b"

[1] "a b"

In [4]:
paste('Hello', "World!")

[1] "Hello World!"

In [8]:
# iris의 1, 51, 101번의 Species를 벡터 하나로 만들기
paste(iris$Species[1], ':', iris$Species[51], ':', iris$Species[101])

[1] "setosa : versicolor : virginica"

In [13]:
paste("010", "1111", "2222", sep = '-')

[1] "010-1111-2222"

# 출력함수

In [15]:
print(head(iris))

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa


In [23]:
# print는 출력 객체가 1개만 허용

print(1)

[1] 1


In [28]:
# 
cat("a",'b','c', "\n")
cat("Hello\n","World!", sep = "")

a b c 
Hello
World!

In [33]:
cat("국어\t\t","영어\t","수학",'\n')
cat("90\t\t",'80\t','70')

국어		 영어	 수학 
90		 80	 70

In [36]:
paste("국어\t\t","영어\t","수학",'\n')

[1] "국어\t\t 영어\t 수학 \n"

# 문자열 추출하기

In [39]:
str01 <- 'a1234fghijklmn'
substring(str01, 2, 5)
str02 <- '1가나다라마바사'
substring(str02, 2, 5)

[1] "1234"

[1] "가나다라"

# 행렬(matrix)

- 2차원 자료를 저장하는 자료형 
- 행렬은 데이터 형태가 모두 일치되어야 구성 

In [40]:
# 벡터를 이용하여 행렬 만들기

vec1 <- c(1,2,3)
vec2 <- c(4,5,6)
vec3 <- c(7,8,9)

In [41]:
# rbind : row bind
mat1 <- rbind(vec1, vec2, vec3)
mat1

[,1] [,2] [,3]
vec1 1    2    3   
vec2 4    5    6   
vec3 7    8    9

In [42]:
# cbind : column bind

mat2 <- cbind(vec1, vec2, vec3)
mat2

vec1 vec2 vec3
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [54]:
# iris의 1~5번 데이터만 추출하기
irisHead <- head(iris, 5)
irisHead

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa

In [55]:
# 새로운 데이터 : 1,1,1,1,setosa 추가하기
irisHead <- rbind(irisHead, c(1,1,1,1,'setosa'))
irisHead

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3           1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5            3.6         1.4          0.2         setosa 
6 1            1           1            1           setosa

In [56]:
# 새로운 특성 : 2,2,2,2,2,2 을 컬럼으로 추가하기, 컬럼명은 abc
abc <- rep(2,6)
cbind(irisHead, abc)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species abc
1 5.1          3.5         1.4          0.2         setosa  2  
2 4.9          3           1.4          0.2         setosa  2  
3 4.7          3.2         1.3          0.2         setosa  2  
4 4.6          3.1         1.5          0.2         setosa  2  
5 5            3.6         1.4          0.2         setosa  2  
6 1            1           1            1           setosa  2

In [58]:
irisHead <- cbind(irisHead, abc=rep(2,6))
irisHead

Sepal.Length Sepal.Width Petal.Length Petal.Width Species abc
1 5.1          3.5         1.4          0.2         setosa  2  
2 4.9          3           1.4          0.2         setosa  2  
3 4.7          3.2         1.3          0.2         setosa  2  
4 4.6          3.1         1.5          0.2         setosa  2  
5 5            3.6         1.4          0.2         setosa  2  
6 1            1           1            1           setosa  2

In [67]:
irisHead <- iris[1:5,]

In [85]:
irisHead$abc <- rep(2,5)
irisHead

Sepal.Length Sepal.Width Petal.Length Petal.Width Species abc
1 5.1          3.5         1.4          0.2         setosa  2  
2 4.9          3.0         1.4          0.2         setosa  2  
3 4.7          3.2         1.3          0.2         setosa  2  
4 4.6          3.1         1.5          0.2         setosa  2  
5 5.0          3.6         1.4          0.2         setosa  2

In [91]:
# Length : Sepal.Length와 Petal.Length의 합계 
irisHead <- iris[1:5,]
irisHead$Length <- irisHead$Sepal.Length + irisHead$Petal.Length
irisHead

Sepal.Length Sepal.Width Petal.Length Petal.Width Species Length
1 5.1          3.5         1.4          0.2         setosa  6.5   
2 4.9          3.0         1.4          0.2         setosa  6.3   
3 4.7          3.2         1.3          0.2         setosa  6.0   
4 4.6          3.1         1.5          0.2         setosa  6.1   
5 5.0          3.6         1.4          0.2         setosa  6.4

In [95]:
# iris에서 Sepal.Length와 Sepal.Width만 추출하여 irisM이라는 데이터프레임 만들기

irisM <- iris[,c('Sepal.Length', 'Sepal.Width')]
head(irisM)
class(irisM)

Sepal.Length Sepal.Width
1 5.1          3.5        
2 4.9          3.0        
3 4.7          3.2        
4 4.6          3.1        
5 5.0          3.6        
6 5.4          3.9

[1] "data.frame"

In [99]:
irisM <- cbind(iris$Sepal.Length, iris$Sepal.Width)
head(irisM)
class(irisM)
irisD <- as.data.frame(irisM)
class(irisD)

[,1] [,2]
[1,] 5.1  3.5 
[2,] 4.9  3.0 
[3,] 4.7  3.2 
[4,] 4.6  3.1 
[5,] 5.0  3.6 
[6,] 5.4  3.9

[1] "matrix"

[1] "data.frame"

In [103]:
# mat1에 컬럼이름 추가 

mat1
colnames(mat1) <- c('A','B','C')
mat1
class(mat1)

mat1D <- as.data.frame(mat1)
class(mat1D)

A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

[1] "matrix"

[1] "data.frame"

In [104]:
str(mat1)

 num [1:3, 1:3] 1 4 7 2 5 8 3 6 9
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:3] "vec1" "vec2" "vec3"
  ..$ : chr [1:3] "A" "B" "C"


In [105]:
str(mat1D)

'data.frame':	3 obs. of  3 variables:
 $ A: num  1 4 7
 $ B: num  2 5 8
 $ C: num  3 6 9


In [106]:
summary(mat1)

       A             B             C      
 Min.   :1.0   Min.   :2.0   Min.   :3.0  
 1st Qu.:2.5   1st Qu.:3.5   1st Qu.:4.5  
 Median :4.0   Median :5.0   Median :6.0  
 Mean   :4.0   Mean   :5.0   Mean   :6.0  
 3rd Qu.:5.5   3rd Qu.:6.5   3rd Qu.:7.5  
 Max.   :7.0   Max.   :8.0   Max.   :9.0  

In [107]:
summary(mat1D)

       A             B             C      
 Min.   :1.0   Min.   :2.0   Min.   :3.0  
 1st Qu.:2.5   1st Qu.:3.5   1st Qu.:4.5  
 Median :4.0   Median :5.0   Median :6.0  
 Mean   :4.0   Mean   :5.0   Mean   :6.0  
 3rd Qu.:5.5   3rd Qu.:6.5   3rd Qu.:7.5  
 Max.   :7.0   Max.   :8.0   Max.   :9.0  

In [113]:
# mat2에 rownames 추가하기

rownames(mat2) <- 1:3
print(mat2)
mat2D <- as.data.frame(mat2)
mat2D

  vec1 vec2 vec3
1    1    4    7
2    2    5    8
3    3    6    9


vec1 vec2 vec3
1 1    4    7   
2 2    5    8   
3 3    6    9

In [124]:
# mat1D와 mat2D를 하나의 DataSet으로 만들기
mat1D
mat2D

# rbind(mat1D, mat2D) 
colnames(mat2D) <- colnames(mat1D)
mat3D <- rbind(mat1D, mat2D)
rownames(mat3D) <- 1:6
tail(mat3D)

A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

A B C
1 1 4 7
2 2 5 8
3 3 6 9

A B C
1 1 2 3
2 4 5 6
3 7 8 9
4 1 4 7
5 2 5 8
6 3 6 9

# 데이터프레임
: 다양한 자료형으로 구성된 2차원 형태의 데이터 구조

In [125]:
# 벡터로 데이터프레임 만들기
no <- 1:4
name <- c("Apple", 'Banana', 'Peach', 'Berry')
price <- c(500, 400, 300, 200)
qty <- c(5, 2, 7, 9)

In [134]:
fruit <- data.frame(번호=no, 상품명=name, 금액=price, 재고량=qty,
                    stringsAsFactors = F
                   )
fruit

번호 상품명 금액 재고량
1 1    Apple  500  5     
2 2    Banana 400  2     
3 3    Peach  300  7     
4 4    Berry  200  9

In [135]:
str(fruit)

'data.frame':	4 obs. of  4 variables:
 $ 번호  : int  1 2 3 4
 $ 상품명: chr  "Apple" "Banana" "Peach" "Berry"
 $ 금액  : num  500 400 300 200
 $ 재고량: num  5 2 7 9


In [137]:
# fruit에서 상품명과 재고량만 보기

fruit[,c(2,4)]

상품명 재고량
1 Apple  5     
2 Banana 2     
3 Peach  7     
4 Berry  9

In [139]:
# fruit에서 번호 컬럼을 제외한 모든 내용 보기

fruit[,-1]

상품명 금액 재고량
1 Apple  500  5     
2 Banana 400  2     
3 Peach  300  7     
4 Berry  200  9

In [143]:
# fruit에서 2,4번 행을 제외한 상품명, 금액, 재고량만 보기

fruit[-c(2,4),-1]

상품명 금액 재고량
1 Apple  500  5     
3 Peach  300  7

In [146]:
# fruit에서 재고금액(금액*재고량) 컬럼을 생성한다.

fruit$재고금액 <- fruit$금액 * fruit$재고량
fruit

번호 상품명 금액 재고량 재고금액
1 1    Apple  500  5      2500    
2 2    Banana 400  2       800    
3 3    Peach  300  7      2100    
4 4    Berry  200  9      1800

In [148]:
# fruit에 원산지(한국, 태국, 한국, 중국) 컬럼 생성하기
fruit$원산지 <- c('한국','태국', '한국', '중국')
fruit

번호 상품명 금액 재고량 재고금액 원산지
1 1    Apple  500  5      2500     한국  
2 2    Banana 400  2       800     태국  
3 3    Peach  300  7      2100     한국  
4 4    Berry  200  9      1800     중국

---
# 외부 File 불러오기

In [169]:
# txt file 불러오기

txtEmp <- read.table("./Data/emp.txt", 
                     header = T, 
                     stringsAsFactors = F,
                     sep="*"
                    )
txtEmp

사번 이름 급여
1 101  hong 150 
2 201  lee  250 
3 301  kim  300

In [166]:
str(txtEmp)

'data.frame':	3 obs. of  3 variables:
 $ 사번: int  101 201 301
 $ 이름: chr  "hong" "lee" "kim"
 $ 급여: int  150 250 300


In [174]:
csvEmp <- read.csv("./Data/emp2.csv", 
                   header = F,
                   stringsAsFactors = F
                  )
colnames(csvEmp) <- c('사번', '이름', '급여')
csvEmp

사번 이름   급여
1 101  홍길동 150 
2 102  이순신 450 
3 103  강감찬 500 
4 104  유관순 350 
5 105  김유신 400

In [175]:
str(csvEmp)

'data.frame':	5 obs. of  3 variables:
 $ 사번: int  101 102 103 104 105
 $ 이름: chr  "홍길동" "이순신" "강감찬" "유관순" ...
 $ 급여: int  150 450 500 350 400


In [176]:
df <- data.frame(x=1:5, y=seq(2,10,2), z=c('a','b','c','d','e'))
df

x y  z
1 1  2 a
2 2  4 b
3 3  6 c
4 4  8 d
5 5 10 e

In [178]:
# x, y의 합계

sum(df$x)
sum(df$y)

[1] 15

[1] 30

# 함수를 부르는 함수

In [179]:
df

x y  z
1 1  2 a
2 2  4 b
3 3  6 c
4 4  8 d
5 5 10 e

In [182]:
# 데이터 프레임에 함수 적용시 행방향 적용
apply(df[,1:2], 1, sum)
apply(df[,1:2], 1, mean)
apply(df[,1:2], 1, sd)

[1]  3  6  9 12 15

[1] 1.5 3.0 4.5 6.0 7.5

[1] 0.7071068 1.4142136 2.1213203 2.8284271 3.5355339

In [183]:
# 데이터 프레임에 함수 적용시 열방향 적용
apply(df[,1:2], 2, sum)
apply(df[,1:2], 2, mean)
apply(df[,1:2], 2, sd)

x  y 
15 30

x y 
3 6

x        y 
1.581139 3.162278

In [185]:
df$Hap <- apply(df[,1:2], 1, sum)
df

x y  z Hap
1 1  2 a  3 
2 2  4 b  6 
3 3  6 c  9 
4 4  8 d 12 
5 5 10 e 15

# 부분집합

In [191]:
# 데이터에 조건을 부여하여 데이터셋 만들기
# x컬럼중 3보다 크고 y컬럼중 8보다 큰 데이터의 갯수는 ?

nrow(subset(df, x>=3 & y>=8))

[1] 2

In [193]:
# iris에서 Sepal.Length가 5.8보다 크고 Sepal.Width가 3.057보다 크고
# Petal.length가 3.758보다 크고 Petal.Width가 1.199보다 큰
# 데이터의 갯수는 ?
subset(iris, Sepal.Length > ... )

  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
       Species  
 setosa    :50  
 versicolor:50  
 virginica :50  
                
                
                

# 2개 이상의 데이터프레임 병합하기

In [196]:
# case 1 : Key값이 되는 컬럼이 동일하고 data의 갯수도 동일한 경우

height <- data.frame(id=1:3, height=c(150, 170, 180))
height
weight <- data.frame(id=c(2,1,3), weight=c(70, 60, 80))
weight

id height
1 1  150   
2 2  170   
3 3  180

id weight
1 2  70    
2 1  60    
3 3  80

In [197]:
merge(height, weight)

id height weight
1 1  150    60    
2 2  170    70    
3 3  180    80

In [199]:
# case 2: key값이 되는 컬럼이 동일하지 않고, 각각의 data갯수도 다를 경우
height <- data.frame(id=1:3, height=c(160, 170, 180))
height
weight <- data.frame(ad=c(2,1), weight=c(70,60))
weight

id height
1 1  160   
2 2  170   
3 3  180

ad weight
1 2  70    
2 1  60

In [200]:
merge(height, weight)

id height ad weight
1 1  160    2  70    
2 2  170    2  70    
3 3  180    2  70    
4 1  160    1  60    
5 2  170    1  60    
6 3  180    1  60

In [201]:
# key를 정의하기 : data가 적은쪽의 기준으로 merge 한다.
merge(x=height, y=weight, by.x = "id", by.y="ad")

id height weight
1 1  160    60    
2 2  170    70

In [203]:
# data가 많은쪽의 기준으로 merge 한다.
merge(x=height, y=weight, by.x='id', by.y='ad', all.x=T)

id height weight
1 1  160    60    
2 2  170    70    
3 3  180    NA

# 행렬 함수로 행렬 만들기

In [206]:
matrix(1:10)
matrix(1:10, nrow = 2)
matrix(1:9, nrow=3, ncol=3)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

# List
- 성격이 다른 자료구조로 생성이 가능하다.
- key와 value값으로 구성된다.  

In [208]:
member <- list(name='홍길동', address='서울', tel='010-1111-2222', pay=300)
member

$name
[1] "홍길동"

$address
[1] "서울"

$tel
[1] "010-1111-2222"

$pay
[1] 300

In [209]:
member$name

[1] "홍길동"

In [210]:
member$birth <- "1988-08-08"
member

$name
[1] "홍길동"

$address
[1] "서울"

$tel
[1] "010-1111-2222"

$pay
[1] 300

$birth
[1] "1988-08-08"

---
# 문자열 처리
수집한 데이터의 필요한 문자열을 자르고, 교체하고, 추출하는 작업      

## stringr package 사용
- str_length() : 문자열 길이
- str_c() : 문자열 연결 
- str_sub() : 범위에 해당하는 문자열 생성 
- str_split() : 구분자를 기준으로 문자열을 분리하여 부분 생성 
- str_replace() : 기존 문자열을 특정 문자열로 변환 
- str_extract() : 문자열에서 특정 문자열 패턴의 첫번째 문자열 추출 
- str_extact_all() : 문자열에서 특정 문자열 패턴의 모둔 문자열 추출 
- str_locate() : 문자열에서 특정 문자열 패턴의 첫번째 위치 추출 
- str_locate_all() : 문자열에서 특정 문자열 패턴의 모든 위치 추출 

In [212]:
# 패키지 불러오기
library(stringr)


Attaching package: ‘stringr’

The following object is masked _by_ ‘.GlobalEnv’:

    fruit



In [213]:
string <- "hongkildong105yoube1002kwanwoo25장비2005"

In [214]:
# a ~ z까지의 영문자가 연속으로 3개 발견된 문자열 추출
str_extract_all(string, "[a-z]{3}")

[[1]]
[1] "hon" "gki" "ldo" "you" "kwa" "nwo"

In [215]:
# a ~ z까지의 영문자가 연속으로 3~5개 발견된 문자열 추출
str_extract_all(string, "[a-z]{3,5}")

[[1]]
[1] "hongk" "ildon" "yoube" "kwanw"

In [216]:
# a ~ z까지의 영문자가 연속으로 1개 이상 발견된 문자열 추출
str_extract_all(string, "[a-z]{1,}")

[[1]]
[1] "hongkildong" "yoube"       "kwanwoo"

In [218]:
# 숫자만 추출하기
str_extract_all(string, "[0-9]{1,}")

[[1]]
[1] "105"  "1002" "25"   "2005"

In [219]:
# 한글만 추출하기
str_extract_all(string, "[가-힣]{1,}")

[[1]]
[1] "장비"

In [220]:
# 영문자를 제외한 문자 출력하기
str_extract_all(string, "[^a-z]{1,}")

[[1]]
[1] "105"        "1002"       "25장비2005"

In [221]:
# 문자열 길이 구하기
str_length(string)

[1] 38

In [223]:
# 문자열 위치 구하기
str_locate(string, "장비")

start end
[1,] 33    34

In [228]:
# 부분 문자열 추출
str_sub(string, 1, 32)
str_sub(string, 1, str_locate(string, "장비")[1] - 1)

[1] "hongkildong105yoube1002kwanwoo25"

[1] "hongkildong105yoube1002kwanwoo25"

In [230]:
# 대문자, 소문자 변경하기
str_to_upper(string)
str_to_lower(string)

[1] "HONGKILDONG105YOUBE1002KWANWOO25장비2005"

[1] "hongkildong105yoube1002kwanwoo25장비2005"

In [232]:
# 문자열 교체하기
string <- str_replace(string, "hongkildong105", "홍길동35,")
string <- str_replace(string, "yoube1002", "유비45,")
string <- str_replace(string, "kwanwoo25", "관우25,")
string <- str_replace(string, "2005", "20")
string

[1] "홍길동35,유비45,관우25,장비20"

In [246]:
# 문자열 분리하기
unlist(str_split(string, ","))

[1] "홍길동35" "유비45"   "관우25"   "장비20"

In [250]:
# 천단위 쉼표가 들어간 문자열을 숫자로 변경하기
price <- "123,456,789"
as.numeric(str_replace_all(price, ",", ""))
as.numeric(str_remove_all(price, ","))

[1] 123456789

[1] 123456789

In [261]:
# Na를 변경하기
temp <- c(1,2,NA, 4)
temp
str_replace_na(temp, mean(temp, na.rm=T))

str_replace_na(temp)
str_replace_all(str_replace_na(temp), 'NA', '99')

[1]  1  2 NA  4

[1] "1"                "2"                "2.33333333333333" "4"

[1] "1"  "2"  "NA" "4"

[1] "1"  "2"  "99" "4"

In [263]:
# Na를 제거하기
temp <- c(1,2,NA, 4)
temp

na.omit(temp)

[1]  1  2 NA  4

[1] 1 2 4
attr(,"na.action")
[1] 3
attr(,"class")
[1] "omit"